l_spanish:
  # Graphics
  SETTING_RENDERER: "Renderizador"
  SETTING_VSYNC: "VSync"
  SETTING_VSYNC_TOOLTIP: "Hace que la frecuencia de fotogramas del juego se sincronice con la frecuencia de actualización de pantalla."
  SETTING_MULTI_SAMPLING: "Multisampling"
  SETTING_MULTI_SAMPLING_TOOLTIP: "Determina la suavidad de los bordes de las imágenes. Los valores más altos resultan en bordes más suaves, pero a costa del rendimiento."
  SETTING_ANISOTROPIC_FILTERING: "Filtrado anisotrópico"
  SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "Los valores más altos mejoran la calidad de las superficies texturizadas en ángulos de visión oblicuos, pero a costa del rendimiento."
  SETTING_FULLSCREEN_RESOLUTION: "Resolución a pantalla completa"
  SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "Resolución del juego. Una mayor resolución requiere más recursos."
  SETTING_WINDOWED_RESOLUTION: "Resolución en ventana"
  SETTING_WINDOWED_RESOLUTION_TOOLTIP: "Resolución del juego. Una mayor resolución requiere más recursos."
  SETTING_DISPLAY: "Pantalla"
  SETTING_DISPLAY_TOOLTIP: "En qué pantalla debe aparecer el juego."
  SETTING_GRAPHICS_DEVICE: "Dispositivo gráfico"
  SETTING_GRAPHICS_DEVICE_TOOLTIP: "Selecciona en qué dispositivo gráfico se ejecutará el juego."
  SETTING_SHADOW_MAP_RESOLUTION: "Resolución de mapas de sombra"
  SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "Determina la resolución con la que se renderizan los mapas de sombras. Valores más altos dan sombras de mejor calidad."
  SETTING_SHADOW_MAP_ENABLED: "Sombras activadas/desactivadas"
  SETTING_SHADOW_MAP_ENABLED_TOOLTIP: "Activa o desactiva las sombras. Desactivar las sombras aumenta el rendimiento."
  SETTING_DISPLAY_MODE: "Modo de visualización"
  SETTING_DISPLAY_MODE_TOOLTIP: "Qué modo de pantalla utilizar."
  SETTING_BLOOM: "Resplandor"
  SETTING_MESH_LOD_BIAS: "Calidad de LOD de malla"
  SETTING_MESH_LOD_FADE: "Difuminación de LOD de malla"
  OPTION_FULLSCREEN: "Pantalla completa"
  OPTION_FULLSCREEN_TOOLTIP: "El juego usará toda la pantalla."
  OPTION_BORDERLESS_FULLSCREEN: "Pantalla completa sin bordes"
  OPTION_BORDERLESS_FULLSCREEN_TOOLTIP: "Una ventana sin bordes con la resolución de tu escritorio."
  OPTION_WINDOWED: "Ventana"
  OPTION_WINDOWED_TOOLTIP: "Una ventana con la resolución ajustada a la configuración de anchura y altura de la ventana."
  OPTION_OFF: "No"
  OPTION_LOW: "Baja"
  OPTION_MEDIUM: "Media"
  OPTION_HIGH: "Alta"
  OPTION_CUSTOM: "Personalizada"
  SETTINGS_CATEGORY_UI:0 "Interfaz"
  SETTINGS_CATEGORY_GAME:0 "Juego"
  SETTING_QUALITY:0 "Configuración de calidad"
  SETTING_SFX:0 "Efectos"
  SETTING_UI:0 "Interfaz de usuario"
  SETTING_QUALITY_TOOLTIP:0 "La selección de una configuración predeterminada de calidad gráfica cambiará automáticamente otras configuraciones gráficas."
  SETTING_BLOOM_TOOLTIP:0 "Habilita o deshabilita un efecto de resplandor."
  SETTING_REFRACTION_TOOLTIP:0 "Determina si las refracciones aparecen o no en el agua."
  SETTING_REFRACTION_QUALITY_TOOLTIP:0 "Controla la calidad de las refracciones del agua si están habilitadas."
  SETTING_MAPOBJECT_QUALITY_TOOLTIP:0 "Determina el nivel de calidad más alto de los objetos del mapa (como las edificaciones)."
  SETTING_MESH_LOD_BIAS_TOOLTIP:0 "Determina la calidad de LOD (niveles de detalle) en los objetos del mapa, como los modelos de unidades."
  SETTING_MESH_LOD_FADE_TOOLTIP:0 "Determina si las alteraciones de LOD (cuando una malla cambia entre una versión de mayor y menor detalle a medida que se modifica la distancia de la cámara) utilizan o no una técnica de transición de difuminación."
  SETTING_PROVINCE_NAMES_TOOLTIP:0 "Determina cómo aparecen los nombres de las ciudades y provincias en el mapa."
  SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Determina si el terreno impasable está incluido dentro de las fronteras de una nación en el mapa."
  SETTING_LANGUAGE_TOOLTIP:0 "Determina el idioma de la interfaz de usuario."
  SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Tu cuenta de correo de Paradox"
  # GUI
  SETTING_ANIMATION_SPEED: "Velocidad de animación"
  SETTING_GUI_SCALING: "Escalado de GUI"
  SETTING_GUI_SCALING_TOOLTIP:0 "Controla la escala de la interfaz de usuario. Útil para resoluciones de pantalla altas."
  # System
  SETTING_MOUSE_PANNING: "Barrido de mouse"
  SETTING_SCROLL_SPEED: "Velocidad de desplazamiento"
  SETTING_CAMERA_ROTATION_SPEED: "Velocidad de rotación de cámara"
  SETTING_ZOOM_SPEED: "Velocidad de zoom"
  SETTING_INPUT_DEVICE: "Dispositivo de entrada"
  SETTING_EDITOR: "Editor"
  SETTING_EDITOR_POSTFIX: "Editor postfijo"
  SETTING_EDITOR_OPEN_FILE_FORMAT: "Comando de apertura del editor"
  SETTING_GRACEFUL_EXIT: "Salida suave"
  SETTING_LANGUAGE: "Idioma"
  MOUSE_AND_KEYBOARD: "Mouse y teclado"
  GAMEPAD: "Control"
  SETTING_MULTISAMPLING_DISABLED: "Desactivado"
  SETTING_ANISOTROPIC_FILTERING_DISABLED: "Desactivado"
  # Editor
  SETTING_CAMERA_TILT: "Inclinación de cámara"
  SETTING_CAMERA_STRATEGY: "Tipo de cámara"
  SETTING_CENTERED_ZOOM_IN: "Zoom centrado"
  SETTING_CAMERA_SPEED: "Velocidad de cámara"
  CAMERA_TABLETOP: "Omnisciente"
  CAMERA_FPS: "Primera persona"
  CAMERA_WASD: "Estilo WASD"
  # Audio
  SETTING_Music: "Música"
  SETTING_Ambient: "Ambiente"
  SETTING_Effects: "Efectos"
  SETTING_Master: "General"
  SETTING_Master_TOOLTIP:0 "Volumen general"
  SETTING_Music_TOOLTIP:0 "Volumen de la música: controla el volumen de la música de fondo."
  SETTING_Ambient_TOOLTIP:0 "Volumen ambiental: controla el volumen del ambiente."
  SETTING_SFX_TOOLTIP:0 "Volumen de los efectos: controla el volumen de los efectos de sonido como el combate."
  SETTING_UI_TOOLTIP:0 "Volumen de la interfaz: controla el volumen de la interfaz de usuario."
  # Game
  SETTING_AUTOSAVE_TOOLTIP:0 "Controla la frecuencia de los autoguardados."
  SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Determina si los autoguardados se guardan en la nube o no."
  SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Determina si la cámara siempre estará orientada hacia el norte o no."
  NO_AUTOSAVE:0 "Sin autoguardado"