l_german:
  # Graphics
  SETTING_RENDERER: "Renderer"
  SETTING_VSYNC: "VSync"
  SETTING_VSYNC_TOOLTIP: "Sorgt dafür, dass die Bildrate des Spiels mit der Bildwiederholungsfrequenz des Monitors synchronisiert."
  SETTING_MULTI_SAMPLING: "Multisampling"
  SETTING_MULTI_SAMPLING_TOOLTIP: "Legt fest, wie glatt die Kanten von Bildern sind. Höhere Werte führen zu glätteren Kanten, jedoch auf Kosten der Leistung."
  SETTING_ANISOTROPIC_FILTERING: "Anisotrope Filterung"
  SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "Höhere Werte verbessern die Qualität von Oberflächen bei schrägen Betrachtungswinkeln, jedoch auf Kosten der Leistung."
  SETTING_FULLSCREEN_RESOLUTION: "Vollbildauflösung"
  SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "Auflösung des Spiels. Eine höhere Auflösung erfordert mehr Leistung."
  SETTING_WINDOWED_RESOLUTION: "Fensterauflösung"
  SETTING_WINDOWED_RESOLUTION_TOOLTIP: "Auflösung des Spiels. Eine höhere Auflösung erfordert mehr Leistung."
  SETTING_DISPLAY: "Anzeige"
  SETTING_DISPLAY_TOOLTIP: "Legt fest, auf welcher Anzeige das Spiel dargestellt werden soll."
  SETTING_GRAPHICS_DEVICE: "Grafikprozessor"
  SETTING_GRAPHICS_DEVICE_TOOLTIP: "Legt fest, auf welchem Grafikprozessor das Spiel laufen soll."
  SETTING_SHADOW_MAP_RESOLUTION: "Auflösung von Schatten"
  SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "Legt fest, mit welcher Auflösung Schatten gerendert werden. Höhere Werte ergeben eine bessere Schattenqualität."
  SETTING_SHADOW_MAP_ENABLED: "Schatten"
  SETTING_SHADOW_MAP_ENABLED_TOOLTIP: "Aktiviert oder deaktiviert Schatten. Das Deaktivieren von Schatten führt zu einer Leistungssteigerung."
  SETTING_DISPLAY_MODE: "Anzeigemodus"
  SETTING_DISPLAY_MODE_TOOLTIP: "Legt fest, welcher Anzeigemodus verwendet werden soll."
  SETTING_BLOOM: "Bloom"
  SETTING_MESH_LOD_BIAS: "Objektqualität"
  SETTING_MESH_LOD_FADE: "Objektübergänge"
  OPTION_FULLSCREEN: "Vollbild"
  OPTION_FULLSCREEN_TOOLTIP: "Das Spiel nutzt den gesamten Bildschirm."
  OPTION_BORDERLESS_FULLSCREEN: "Rahmenloses Fenster"
  OPTION_BORDERLESS_FULLSCREEN_TOOLTIP: "Ein rahmenloses Fenster mit der Auflösung des Desktops."
  OPTION_WINDOWED: "Fenster"
  OPTION_WINDOWED_TOOLTIP: "Ein Fenster mit eingestellter Auflösung für Breite und Höhe des Fensters."
  OPTION_OFF: "Aus"
  OPTION_LOW: "Niedrig"
  OPTION_MEDIUM: "Mittel"
  OPTION_HIGH: "Hoch"
  OPTION_CUSTOM: "Benutzerdefiniert"
  SETTINGS_CATEGORY_UI:0 "Benutzeroberfläche"
  SETTINGS_CATEGORY_GAME:0 "Spiel"
  SETTING_QUALITY:0 "Qualitätsvoreinstellung"
  SETTING_SFX:0 "SFX"
  SETTING_UI:0 "Benutzeroberfläche"
  SETTING_QUALITY_TOOLTIP:0 "Die Auswahl einer Qualitätsvoreinstellung für Grafik ändert andere Grafikeinstellungen automatisch." 
  SETTING_BLOOM_TOOLTIP:0 "Aktiviert oder deaktiviert den Bloom-Effekt."
  SETTING_REFRACTION_TOOLTIP:0 "Bestimmt, ob Reflexionen auf dem Wasser erscheinen oder nicht."
  SETTING_REFRACTION_QUALITY_TOOLTIP:0 "Steuert die Qualität der Wasserreflexion, falls diese aktiviert ist."
  SETTING_MAPOBJECT_QUALITY_TOOLTIP:0 "Bestimmt die höchste Qualitätsstufe von Kartenobjekten (z. B. Gebäuden)."
  SETTING_MESH_LOD_BIAS_TOOLTIP:0 "Bestimmt die Detailqualität für Kartenobjekte wie Einheitenmodelle."
  SETTING_MESH_LOD_FADE_TOOLTIP:0 "Bestimmt, ob bei einer Änderung des Detailgrad (da, wo ein Mesh-Objekt zwischen einer höheren und niedrigeren Detailversion wechselt, wenn sich die Kameraentfernung ändert) Fading-Übergangstechniken verwendet werden sollen oder nicht."
  SETTING_PROVINCE_NAMES_TOOLTIP:0 "Legt fest, wie Stadt- und Provinznamen auf der Karte angezeigt werden."
  SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Bestimmt, ob nicht passierbares Terrain innerhalb der Grenzen einer Nation auf der Karte enthalten sind oder nicht."
  SETTING_LANGUAGE_TOOLTIP:0 "Bestimmt die Sprache der Benutzeroberfläche."
  SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "E-Mail Eures Paradox-Accounts"
  # GUI
  SETTING_ANIMATION_SPEED: "Animationsgeschwindigkeit"
  SETTING_GUI_SCALING: "Skalierung"
  SETTING_GUI_SCALING_TOOLTIP:0 "Steuert die Skalierung der Benutzeroberfläche. Nützlich für höhere Bildschirmauflösungen." 
  # System
  SETTING_MOUSE_PANNING: "Schwenkgeschwindigkeit der Maus"
  SETTING_SCROLL_SPEED: "Scrollgeschwindigkeit"
  SETTING_CAMERA_ROTATION_SPEED: "Bewegungsgeschwindigkeit der Kamera"
  SETTING_ZOOM_SPEED: "Zoomgeschwindigkeit"
  SETTING_INPUT_DEVICE: "Eingabegerät"
  SETTING_EDITOR: "Editor"
  SETTING_EDITOR_POSTFIX: "Editor-Postfix"
  SETTING_EDITOR_OPEN_FILE_FORMAT: "Taste zum Öffnen des Editors"
  SETTING_GRACEFUL_EXIT: "Kontrollierte Beendigung"
  SETTING_LANGUAGE: "Anzeigesprache"
  MOUSE_AND_KEYBOARD: "Maus & Tastatur"
  GAMEPAD: "Gamepad"
  SETTING_MULTISAMPLING_DISABLED: "Deaktiviert"
  SETTING_ANISOTROPIC_FILTERING_DISABLED: "Deaktiviert"
 # Editor
  SETTING_CAMERA_TILT: "Kameraneigung"
  SETTING_CAMERA_STRATEGY: "Kameratyp"
  SETTING_CENTERED_ZOOM_IN: "Zentrierter Zoom"
  SETTING_CAMERA_SPEED: "Kamerageschwindigkeit"
  CAMERA_TABLETOP: "Vogelperspektive"
  CAMERA_FPS: "Egoperspektive"
  CAMERA_WASD: "WASD-Stil"
  # Audio
  SETTING_Music: "Musik"
  SETTING_Ambient: "Umgebung"
  SETTING_Effects: "Effekte"
  SETTING_Master: "Gesamtlautstärke"
  SETTING_Master_TOOLTIP:0 "Gesamtlautstärke"
  SETTING_Music_TOOLTIP:0 "Musiklautstärke - Steuert die Lautstärke der Hintergrundmusik."
  SETTING_Ambient_TOOLTIP:0 "Umgebungslautstärke - Steuert die Lautstärke der Umgebungsatmosphäre."
  SETTING_SFX_TOOLTIP:0 "SFX-Lautstärke - Steuert die Lautstärke von Soundeffekten, z. B. Kampf."
  SETTING_UI_TOOLTIP:0 "UI-Lautstärke - Steuert die Lautstärke der Benutzeroberfläche."
  # Game
  SETTING_AUTOSAVE_TOOLTIP:0 "Steuert die Häufigkeit der automatischen Speicherung."
  SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Legt fest, ob automatische Speicherstände in der Cloud gespeichert werden oder nicht." 
  SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Legt fest, ob die Kamera immer nach Norden zeigt oder nicht."
  NO_AUTOSAVE:0 "Kein Auto. Speichern"