l_english:
  # Graphics
  SETTING_RENDERER: "Renderer"
  SETTING_VSYNC: "VSync"
  SETTING_VSYNC_TOOLTIP: "Makes the game's frame rate syncronize with the refresh rate of your monitor."
  SETTING_MULTI_SAMPLING: "Multisampling"
  SETTING_MULTI_SAMPLING_TOOLTIP: "Determines how smooth edges of images are. Higher values result in smoother edges, but at the cost of performance."
  SETTING_ANISOTROPIC_FILTERING: "Anisotropic filtering"
  SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "Higher values enhances the quality of textured surfaces at oblique viewing angles, but at the cost of performance."
  SETTING_FULLSCREEN_RESOLUTION: "Fullscreen Resolution"
  SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "Resolution of the game. Higher resolution is more demanding."
  SETTING_WINDOWED_RESOLUTION: "Windowed Resolution"
  SETTING_WINDOWED_RESOLUTION_TOOLTIP: "Resolution of the game. Higher resolution is more demanding."
  SETTING_DISPLAY: "Display"
  SETTING_DISPLAY_TOOLTIP: "What display the game should appear on."
  SETTING_GRAPHICS_DEVICE: "Graphics device"
  SETTING_GRAPHICS_DEVICE_TOOLTIP: "Selects which graphics device the game will run on."
  SETTING_SHADOW_MAP_RESOLUTION: "Shadowmap resolution"
  SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "Determines the resolution shadow maps are rendered with. Higher values gives better quality shadows."
  SETTING_SHADOW_MAP_ENABLED: "Shadows enabled/disabled"
  SETTING_SHADOW_MAP_ENABLED_TOOLTIP: "Enables or disables shadows. Disabling shadows gives a performance boost"
  SETTING_DISPLAY_MODE: "Display mode"
  SETTING_DISPLAY_MODE_TOOLTIP: "What kind of display mode to use."
  SETTING_BLOOM: "Bloom"
  SETTING_MESH_LOD_BIAS: "Mesh Lod Quality"
  SETTING_MESH_LOD_FADE: "Mesh Lod Fade"
  OPTION_FULLSCREEN: "Fullscreen"
  OPTION_FULLSCREEN_TOOLTIP: "The game will use the whole screen."
  OPTION_BORDERLESS_FULLSCREEN: "Borderless fullscreen"
  OPTION_BORDERLESS_FULLSCREEN_TOOLTIP: "A borderless window with the resolution of your desktop."
  OPTION_WINDOWED: "Window"
  OPTION_WINDOWED_TOOLTIP: "A window with the resolution set with the windowed width and height settings."
  OPTION_OFF: "Off"
  OPTION_LOW: "Low"
  OPTION_MEDIUM: "Medium"
  OPTION_HIGH: "High"
  OPTION_CUSTOM: "Custom"
  SETTINGS_CATEGORY_UI:0 "Interface"
  SETTINGS_CATEGORY_GAME:0 "Game"
  SETTING_QUALITY:0 "Quality Preset"
  SETTING_SFX:0 "SFX"
  SETTING_UI:0 "UI"
  SETTING_QUALITY_TOOLTIP:0 "Selecting a graphical quality preset will automatically change other graphical settings." 
  SETTING_BLOOM_TOOLTIP:0 "Enables or disables a bloom effect."
  SETTING_REFRACTION_TOOLTIP:0 "Determines whether refractions appear on water or not."
  SETTING_REFRACTION_QUALITY_TOOLTIP:0 "Controls the quality of water refractions if they are enabled."
  SETTING_MAPOBJECT_QUALITY_TOOLTIP:0 "Determines the highest quality level of Map Objects (such as buildings)."
  SETTING_MESH_LOD_BIAS_TOOLTIP:0 "Determines the quality of LODs (Levels of detail) on map objects such as Unit models."
  SETTING_MESH_LOD_FADE_TOOLTIP:0 "Determines whether LOD changes (where a mesh transitions between a higher and lower detail version as camera distance changes) use a fading transition technique or not."
  SETTING_PROVINCE_NAMES_TOOLTIP:0 "Determines how City and Province names appear on the map."
  SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Determines if impassable terrain is included within a nation's borders on the map."
  SETTING_LANGUAGE_TOOLTIP:0 "Determines the Language of the User Interface."
  SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Your Paradox Account email"
  # GUI
  SETTING_ANIMATION_SPEED: "Animation speed"
  SETTING_GUI_SCALING: "GUI Scaling"
  SETTING_GUI_SCALING_TOOLTIP:0 "Controls the scaling of the UI. Useful for higher screen resolutions." 
  # System
  SETTING_MOUSE_PANNING: "Mouse panning"
  SETTING_SCROLL_SPEED: "Scroll speed"
  SETTING_CAMERA_ROTATION_SPEED: "Camera rotation speed"
  SETTING_ZOOM_SPEED: "Zoom speed"
  SETTING_INPUT_DEVICE: "Input device"
  SETTING_EDITOR: "Editor"
  SETTING_EDITOR_POSTFIX: "Editor postfix"
  SETTING_EDITOR_OPEN_FILE_FORMAT: "Editor open command"
  SETTING_GRACEFUL_EXIT: "Graceful exit"
  SETTING_LANGUAGE: "Language"
  MOUSE_AND_KEYBOARD: "Mouse and keyboard"
  GAMEPAD: "Gamepad"
  SETTING_MULTISAMPLING_DISABLED: "Disabled"
  SETTING_ANISOTROPIC_FILTERING_DISABLED: "Disabled"
  # Editor
  SETTING_CAMERA_TILT: "Camera tilt"
  SETTING_CAMERA_STRATEGY: "Camera type"
  SETTING_CENTERED_ZOOM_IN: "Centered zoom-in"
  SETTING_CAMERA_SPEED: "Camera speed"
  CAMERA_TABLETOP: "Table top"
  CAMERA_FPS: "First person"
  CAMERA_WASD: "WASD-style"
  # Audio
  SETTING_Music: "Music"
  SETTING_Ambient: "Ambient"
  SETTING_Effects: "Effects"
  SETTING_Master: "Master"
  SETTING_Master_TOOLTIP:0 "Master Volume"
  SETTING_Music_TOOLTIP:0 "Music Volume - Controls the volume of background music."
  SETTING_Ambient_TOOLTIP:0 "Ambient Volume - Controls the volume of environmental ambience."
  SETTING_SFX_TOOLTIP:0 "SFX Volume - Controls the volume of sound effects such as combat."
  SETTING_UI_TOOLTIP:0 "UI Volume - Controls the volume of the user interface."
  # Game
  SETTING_AUTOSAVE_TOOLTIP:0 "Controls the freqeuncy of Autosaves."
  SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Determines whether Autosaves are saved to the cloud or not." 
  SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Determines whether the Camera will always face North or not."
  NO_AUTOSAVE:0 "No Autosave"