l_russian:
 SETTING_RENDERER:0 "Рендеринг"
 SETTING_VSYNC:0 "Вертикальная синхронизация"
 SETTING_VSYNC_TOOLTIP:0 "Синхронизирует частоту кадров игры с частотой обновления монитора."
 SETTING_MULTI_SAMPLING:0 "Сглаживание"
 SETTING_MULTI_SAMPLING_TOOLTIP:0 "Задаёт степень сглаживания краёв изображения. Чем выше значение, тем лучше сглажено изображение и тем ниже производительность игры."
 SETTING_ANISOTROPIC_FILTERING:0 "Анизотропная фильтрация"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:0 "Чем выше значение, тем выше качество изображения текстурированных поверхностей под острым углом и тем ниже при этом производительность игры."
 SETTING_FULLSCREEN_RESOLUTION:0 "Полноэкранное разрешение"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:0 "Разрешение экрана в игре. Чем выше разрешение, тем больше нагрузка на систему."
 SETTING_WINDOWED_RESOLUTION:0 "Разрешение в оконном режиме"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:0 "Разрешение экрана в игре. Чем выше разрешение, тем больше нагрузка на систему."
 SETTING_DISPLAY:0 "Дисплей"
 SETTING_DISPLAY_TOOLTIP:0 "На каком дисплее должна отображаться игра."
 SETTING_GRAPHICS_DEVICE:0 "Графическое устройство"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:0 "На каком графическом устройстве должна работать игра."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Разрешение карты теней"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:0 "Разрешение, с которым накладываются карты теней. Чем выше это значение, тем качественнее тени."
 SETTING_SHADOW_MAP_ENABLED:0 "Тени"
 SETTING_SHADOW_MAP_ENABLED_TOOLTIP:0 "Включить или выключить тени. Отключение теней повышает производительность игры."
 SETTING_DISPLAY_MODE:0 "Режим отображения"
 SETTING_DISPLAY_MODE_TOOLTIP:0 "Какой режим отображения использовать."
 SETTING_BLOOM:0 "Свечение"
 SETTING_MESH_LOD_BIAS:0 "Качество детализации сетки"
 SETTING_MESH_LOD_FADE:0 "Убывание детализации сетки"
 OPTION_FULLSCREEN:0 "Полноэкранный"
 OPTION_FULLSCREEN_TOOLTIP:0 "Игра задействует весь экран."
 OPTION_BORDERLESS_FULLSCREEN:0 "Полноэкранный без границ"
 OPTION_BORDERLESS_FULLSCREEN_TOOLTIP:0 "Игра выводится в неограниченном окне, чьи размеры равны разрешению монитора."
 OPTION_WINDOWED:0 "Оконный режим"
 OPTION_WINDOWED_TOOLTIP:0 "Игра выводится в окне с заданными высотой и шириной."
 OPTION_OFF:0 "Выкл."
 OPTION_LOW:0 "Низкий"
 OPTION_MEDIUM:0 "Средне"
 OPTION_HIGH:0 "Высокий"
 OPTION_CUSTOM:0 "Пользовательский"
 SETTINGS_CATEGORY_UI:0 "Интерфейс"
 SETTINGS_CATEGORY_GAME:0 "Игра"
 SETTING_QUALITY:0 "Сохранённая настройка качества"
 SETTING_SFX:0 "Звуковые эффекты"
 SETTING_UI:0 "Интерфейс"
 SETTING_QUALITY_TOOLTIP:0 "При выборе сохранённых настроек качества будут автоматически изменены другие графические параметры."
 SETTING_BLOOM_TOOLTIP:0 "Включить или выключить эффект свечения."
 SETTING_REFRACTION_TOOLTIP:0 "Отображать (или нет) отражения на воде."
 SETTING_REFRACTION_QUALITY_TOOLTIP:0 "Качество отражений на воде (если они отображаются)."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:0 "Максимальный уровень качества отображения объектов на карте (здания и т. п.)."
 SETTING_MESH_LOD_BIAS_TOOLTIP:0 "Качество детализации объектов на карте (подразделения и т. п.)."
 SETTING_MESH_LOD_FADE_TOOLTIP:0 "Использовать (или нет) технику перехода с затуханием при изменении уровня детализации объектов."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Способ показывать на карте названия городов и провинций."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Включать (или нет) в границы державы на карте непроходимые участки."
 SETTING_LANGUAGE_TOOLTIP:0 "Язык пользовательского интерфейса."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Адрес вашей эл. почты для учётной записи Paradox"
 SETTING_ANIMATION_SPEED:0 "Скорость анимации"
 SETTING_GUI_SCALING:0 "Масштабирование интерфейса"
 SETTING_GUI_SCALING_TOOLTIP:0 "Управление масштабированием интерфейса. Удобно для больших разрешений экрана."
 SETTING_MOUSE_PANNING:0 "Перемещение камеры мышью"
 SETTING_SCROLL_SPEED:0 "Скорость прокрутки"
 SETTING_CAMERA_ROTATION_SPEED:0 "Скорость вращения камеры"
 SETTING_ZOOM_SPEED:0 "Скорость приближения"
 SETTING_INPUT_DEVICE:0 "Устройство ввода"
 SETTING_EDITOR:0 "Редактор"
 SETTING_EDITOR_POSTFIX:0 "Постфикс для команды редактора"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Команда открытия редактора"
 SETTING_GRACEFUL_EXIT:0 "Выход при ошибке"
 SETTING_LANGUAGE:0 "Язык"
 MOUSE_AND_KEYBOARD:0 "Клавиатура и мышь"
 GAMEPAD:0 "Геймпад"
 SETTING_MULTISAMPLING_DISABLED:0 "Отключено"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Отключено"
 SETTING_CAMERA_TILT:0 "Наклон камеры"
 SETTING_CAMERA_STRATEGY:0 "Тип камеры"
 SETTING_CENTERED_ZOOM_IN:0 "Приближение с центрированием"
 SETTING_CAMERA_SPEED:0 "Скорость камеры"
 CAMERA_TABLETOP:0 "Настольный вид"
 CAMERA_FPS:0 "От первого лица"
 CAMERA_WASD:0 "Стиль WASD"
 SETTING_Music:0 "Музыка"
 SETTING_Ambient:0 "Звуковое сопровождение"
 SETTING_Effects:0 "Эффекты"
 SETTING_Master:0 "Общий уровень"
 SETTING_Master_TOOLTIP:0 "Основная громкость"
 SETTING_Music_TOOLTIP:0 "Громкость музыки — уровень громкости фоновой музыки."
 SETTING_Ambient_TOOLTIP:0 "Звуковое сопровождение — уровень громкости звукового сопровождения."
 SETTING_SFX_TOOLTIP:0 "Звуковые эффекты — уровень громкости звуковых эффектов (боя и так далее)."
 SETTING_UI_TOOLTIP:0 "Интерфейс — уровень громкости звуков элементов интерфейса."
 SETTING_AUTOSAVE_TOOLTIP:0 "Частота автосохранений."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Записывать автосохранения в облако (или нет)."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Всегда разворачивать игровую камеру на север или нет."
 NO_AUTOSAVE:0 "Без автосохранений"
