l_french:
  # Graphics
  SETTING_RENDERER: "Rendu"
  SETTING_VSYNC: "VSync"
  SETTING_VSYNC_TOOLTIP: "Synchronise le taux de rafraîchissement du jeu avec celui du moniteur."
  SETTING_MULTI_SAMPLING: "Multi-échantillonnage"
  SETTING_MULTI_SAMPLING_TOOLTIP: "Détermine la douceur des bords des images. Des valeurs plus élevées permettent des bords plus doux, mais au prix de performances réduites."
  SETTING_ANISOTROPIC_FILTERING: "Filtrage anisotrope"
  SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "Des valeurs plus élevées améliorent la qualité des textures de surface en vue oblique, mais au prix de performances réduites."
  SETTING_FULLSCREEN_RESOLUTION: "Résolution du plein écran"
  SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "Résolution du jeu. Une meilleure résolution est aussi plus exigeante."
  SETTING_WINDOWED_RESOLUTION: "Résolution du mode fenêtré"
  SETTING_WINDOWED_RESOLUTION_TOOLTIP: "Résolution du jeu. Une meilleure résolution est aussi plus exigeante."
  SETTING_DISPLAY: "Affichage"
  SETTING_DISPLAY_TOOLTIP: "Périphérique d'affichage du jeu."
  SETTING_GRAPHICS_DEVICE: "Carte graphique"
  SETTING_GRAPHICS_DEVICE_TOOLTIP: "Sélectionne la carte graphique qui sera utilisée par le jeu."
  SETTING_SHADOW_MAP_RESOLUTION: "Textures d'ombre"
  SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "Détermine la résolution du rendu des textures d'ombre. Des valeurs plus élevées améliorent la qualité des ombres."
  SETTING_SHADOW_MAP_ENABLED: "Ombrages activés/désactivés"
  SETTING_SHADOW_MAP_ENABLED_TOOLTIP: "Active ou désactive les ombrages. Désactiver cette fonction améliore les performances."
  SETTING_DISPLAY_MODE: "Mode d'affichage"
  SETTING_DISPLAY_MODE_TOOLTIP: "Mode d'affichage à utiliser."
  SETTING_BLOOM: "Flou lumineux"
  SETTING_MESH_LOD_BIAS: "Qualité de détail des mesh"
  SETTING_MESH_LOD_FADE: "Transition du niveau de détails des mesh"
  OPTION_FULLSCREEN: "Plein écran"
  OPTION_FULLSCREEN_TOOLTIP: "Le jeu sera affiché sur tout l'écran."
  OPTION_BORDERLESS_FULLSCREEN: "Plein écran sans bordure"
  OPTION_BORDERLESS_FULLSCREEN_TOOLTIP: "Une fenêtre sans bordure, dont la résolution sera celle du bureau."
  OPTION_WINDOWED: "Fenêtre"
  OPTION_WINDOWED_TOOLTIP: "Une fenêtre avec bordures, dont la résolution sera définie par les paramètres de hauteur et de largeur de la fenêtre."
  OPTION_OFF: "Désactivé"
  OPTION_LOW: "Bas"
  OPTION_MEDIUM: "Moyen"
  OPTION_HIGH: "Haut"
  OPTION_CUSTOM: "Personnalisé"
  SETTINGS_CATEGORY_UI:0 "Interfaces"
  SETTINGS_CATEGORY_GAME:0 "Jeu"
  SETTING_QUALITY:0 "Préréglages qualité"
  SETTING_SFX:0 "Effets sonores"
  SETTING_UI:0 "Interfaces"
  SETTING_QUALITY_TOOLTIP:0 "Le choix de la qualité des graphismes va automatiquement modifier les autres paramètres graphiques." 
  SETTING_BLOOM_TOOLTIP:0 "Active ou non un effet de flou lumineux."
  SETTING_REFRACTION_TOOLTIP:0 "Détermine si les reflets apparaissent ou non sur l'eau."
  SETTING_REFRACTION_QUALITY_TOOLTIP:0 "Contrôle la qualité des reflets sur l'eau, si ceux-ci sont activés."
  SETTING_MAPOBJECT_QUALITY_TOOLTIP:0 "Détermine le meilleur niveau de qualité pour les objets affichés sur la carte, tels que les bâtiments."
  SETTING_MESH_LOD_BIAS_TOOLTIP:0 "Détermine le niveau de détail, et donc la qualité des objets affichés sur la carte, tels que les modèles d'unités."
  SETTING_MESH_LOD_FADE_TOOLTIP:0 "Détermine si les changements dans le niveau de détail (par exemple lors de l'éloignement ou du rapprochement de la caméra) doivent utiliser une technologie de transition ou non."
  SETTING_PROVINCE_NAMES_TOOLTIP:0 "Définit la façon dont les noms des cités et provinces sont affichés sur la carte."
  SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Définit si, sur la carte, le terrain infranchissable est inclus au sein des frontières des pays limitrophes."
  SETTING_LANGUAGE_TOOLTIP:0 "Choix de la langue dans laquelle la partie sera jouée."
  SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Adresse e-mail utilisée lors de la création du compte Paradox."
  # GUI
  SETTING_ANIMATION_SPEED: "Vitesse des animations"
  SETTING_GUI_SCALING: "Échelle des interfaces"
  SETTING_GUI_SCALING_TOOLTIP:0 "Permet d'augmenter ou diminuer la taille des interfaces en jeu, ce qui est très utile pour les écrans à haute résolution."
  # System
  SETTING_MOUSE_PANNING: "Panoramique de la souris"
  SETTING_SCROLL_SPEED: "Vitesse de défilement"
  SETTING_CAMERA_ROTATION_SPEED: "Vitesse de rotation de la caméra"
  SETTING_ZOOM_SPEED: "Vitesse du zoom"
  SETTING_INPUT_DEVICE: "Contrôles"
  SETTING_EDITOR: "Éditeur"
  SETTING_EDITOR_POSTFIX: "Éditeur de postfix"
  SETTING_EDITOR_OPEN_FILE_FORMAT: "Commandes de l'éditeur"
  SETTING_GRACEFUL_EXIT: "Sortie"
  SETTING_LANGUAGE: "Langue"
  MOUSE_AND_KEYBOARD: "Souris et clavier"
  GAMEPAD: "Manette"
  SETTING_MULTISAMPLING_DISABLED: "Désactivé"
  SETTING_ANISOTROPIC_FILTERING_DISABLED: "Désactivé"
  # Editor
  SETTING_CAMERA_TILT: "Panoramique caméra"
  SETTING_CAMERA_STRATEGY: "Type de caméra"
  SETTING_CENTERED_ZOOM_IN: "Centrer sur le zoom"
  SETTING_CAMERA_SPEED: "Vitesse de la caméra"
  CAMERA_TABLETOP: "Jeu de plateau"
  CAMERA_FPS: "Première personne"
  CAMERA_WASD: "Type ZQSD"
  # Audio
  SETTING_Music: "Musiques"
  SETTING_Ambient: "Sons d'ambiance"
  SETTING_Effects: "Effets"
  SETTING_Master: "Volume principal"
  SETTING_Master_TOOLTIP:0 "Réglage du volume principal."
  SETTING_Music_TOOLTIP:0 "Réglage du volume de la musique en fond sonore."
  SETTING_Ambient_TOOLTIP:0 "Réglage du volume des sons d'ambiance produits par l'environnement."
  SETTING_SFX_TOOLTIP:0 "Réglage du volume des effets sonores, tels que ceux produits par les combats."
  SETTING_UI_TOOLTIP:0 "Réglage du volume des sons produits par les interfaces du jeu."
  # Game
  SETTING_AUTOSAVE_TOOLTIP:0 "Contrôle la fréquence des sauvegardes automatiques."
  SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Définit si les sauvegardes automatiques doivent ou non être enregistrées sur le cloud." 
  SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Définit si la caméra doit ou non toujours être dirigée vers le nord."
  NO_AUTOSAVE:0 "Aucune sauv. auto."
