NDefines.NCountry.NUCLEAR_BOMB_DROP_WAR_SUPPORT_EFFECT_MAX_INFRA = 10.0; 
NDefines.NCountry.NUCLEAR_BOMB_DROP_WAR_SUPPORT_EFFECT_MAX_VP = 10;
NDefines.NMilitary.NUKE_MIN_DAMAGE_PERCENT = 1.2;
NDefines.NMilitary.NUKE_MAX_DAMAGE_PERCENT = 1.2;
NDefines.NCountry.NUCLEAR_PRODUCTION_SCALE = 730;
