l_spanish:
 PRODUCTION_EFFICIENCY_MOD:0 "£prod_eff §TEficacia de producción: $AMOUNT|Y2%$§!\n"
 PRODUCTION_EQUIPMENT_TOTAL_NEED:2 "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE:0 "Balance diario: $VALUE|=2Y$"
 PRODUCTION_OUTPUT_EXPLAIN:0 "Nuestras $FACTORIES|Y$ £factory_item  fábricas militares aportan $OUTPUT|Y$ £production_cost . \n$ITEM|Y$ tiene un coste de $ITEM_COST|2Y$ £production_cost , por lo que podemos producir $PERTIMEPERIOD$.\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL:0 "Nuestros $FACTORIES|Y$ £naval_factory_icon  astilleros navales aportan £navprod_cost  $OUTPUT|Y$.\n$ITEM|Y$ tiene un coste de $ITEM_COST|2Y$ £navprod_cost , por lo que podemos producir $PERTIMEPERIOD$.\n"
 PROD_COST_VALUE:0 "£production_cost  $VALUE$"
 INDUSTRIAL_BASE_FACTORY_OUTPUT:0 "Rendimiento de fábrica base: $VALUE|H$"
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE:0 " Disponible para construcción: $VALUE|Y$"
 PRODUCTION_MATERIAL_COST_LACKING_DESC:0 "§TNecesita $AMOUNT|0H$ unidades más para funcionar a plena capacidad.§!\n"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 PRODUCTION_MATERIAL_VAL:0 "$VALUE|0H$"
 PRODUCTION_CONSUMER_GOODS_VALUE:0 "$VALUE$"
 TRADE_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 INFINITY:0 "£infinity_icon"
 NAVPROD_COST_VALUE:0 "£navprod_cost  $VALUE$"
 CARRIER_AIR_WING_LIMIT_UNDER:0 "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH:0 "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER:0 "$COUNT|R$/$LIMIT$"
 PRODUCTION_CAN_NOT_DEPLOY:0 "§RImposible desplegar§!"
 PRODUCTION_VARIANT_OBSOLETE_YES:0 "Esta variante está marcada como obsoleta"
 PRODUCTION_VARIANT_OBSOLETE_NO:0 "Esta variante no está marcada como obsoleta"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC:0 "§GHaz clic§! para reactivar esta variante y marcarla como equipo actualizado."
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC:0 "§GHaz clic§! para cancelar esta variante y marcarla como equipo obsoleto."
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE:0 "Cambiar equipo"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC:0 "¿Seguro que quieres §Rcambiar§! el equipo? Perderás $DAYS|R$ días de producción."
 PRODUCTION_PRODUCTION_LABEL:0 "Producción"
 PRODUCTION_EQUIPMENTPOOL_LABEL:0 "Almacenamiento"
 PRODUCTION_EFFICIENCY_LABEL:0 "§TEficacia§!"
 PRODUCTION_EQUIPMENT_LABEL:0 "Equipo"
 PRODUCTION_ADJUSTERS_LABEL:0 "Reguladores"
 PRODUCTION_MATERIALS_LABEL:0 "Materiales"
 PRODUCTION_FACTORIES_LABEL:0 "Fábricas"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL:0 "Fábricas militares"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL:0 "Astilleros navales"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "Fábricas civiles"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL:0 "Fábricas militares disponibles"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL:0 "Astilleros navales disponibles"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL:0 "Fábricas civiles disponibles"
 PRODUCTION_MILITARY_LABEL:0 "§TEquipo de ejército y fuerza aérea§!"
 PRODUCTION_NAVAL_LABEL:0 "§TEquipo naval§!"
 PRODUCTION_BUILDINGS_LABEL:0 "§TConstrucción de edificios§!"
 PRODUCTION_PRODUCING_DAILY:0 "$AMOUNT$/día"
 PRODUCTION_PRODUCING_WEEKLY:0 "$AMOUNT$/semana"
 PRODUCTION_PRODUCING_MONTHLY:0 "$AMOUNT$/mes"
 PRODUCTION_PRODUCING_YEARLY:0 "$AMOUNT$/año"
 PRODUCTION_PRODUCING_ETA_DATE:0 "Siguiente tanda: $DATE$"
 PRODUCTION_REPAIRING_ETA_DATE:0 "Reparación completada: $DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS:0 "En $AMOUNT$ días"
 PRODUCTION_PRODUCING_ETA_WEEKS:0 "En $AMOUNT$ semanas"
 PRODUCTION_PRODUCING_ETA_MONTHS:0 "En $AMOUNT$ meses"
 PRODUCTION_PRODUCING_ETA_YEARS:0 "En $AMOUNT$ años"
 PRODUCTION_PRODUCING_NEVER:1 "§RNunca§!"
 PRODUCTION_PRODUCING_NONE:0 "§RNada§!"
 PRODUCTION_INCREASE_PRIORITY_LABEL:0 "§GHaz clic para §Haumentar la prioridad§!.\nMayús + clic para dar la §Hmáxima prioridad§! a la producción.§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL:0 "§GHaz clic para §Hreducir la prioridad§!.\nMayús + clic para dar la §Hprioridad más baja§! a la producción.§!"
 PRODUCTION_PRIORITY_DELAYED:0 "Una cadena de producción con más prioridad accederá a los recursos antes que aquellas con una prioridad más baja."
 PRODUCTION_EFFICIENCY:0 "£prod_eff  §TEficacia de producción: $AMOUNT|H2%$§!"
 PRODUCTION_EFFICIENCY_WITH_GAIN:2 "£prod_eff  §TEficacia de producción: $AMOUNT|H2%$§! ($GAIN|H3%$ al día)"
 PRODUCTION_EFFICIENCY_DESC:0 "§TEficacia media de producción de fábrica.\nLa eficacia de producción aumenta en $VALUE|H=2$%/unidad producida dividida a partes iguales en fábricas activas.§!"
 PRODUCTION_RESOURCE_PENALTY:0 "§TFalta de recursos: $AMOUNT|R2%$§!"
 PRODUCTION_ASSIGN_EQUIPMENT:0 "§TAsigna equipo para iniciar la producción.§!"
 PRODUCTION_MATERIALS_OIL:0 "Petróleo"
 PRODUCTION_MATERIALS_ALUMINIUM:0 "Aluminio"
 PRODUCTION_MATERIALS_RUBBER:0 "Caucho"
 PRODUCTION_MATERIALS_CHROMIUM:0 "Cromo"
 PRODUCTION_MATERIALS_STEEL:0 "Acero"
 PRODUCTION_MATERIALS_TUNGSTEN:0 "Wolframio"
 PRODUCTION_VEHICLES_BUTTON:0 "Construir vehículos blindados"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "¡Vehículos blindados §Rno inventados§!!"
 PRODUCTION_INFANTRY_BUTTON:0 "Construir equipo de infantería y artillería"
 PRODUCTION_INFANTRY_BUTTON_DISABLED:0 "¡Equipo de infantería y artillería §Rno inventado§!!"
 PRODUCTION_AIRCRAFT_BUTTON:0 "Construir aviones"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED:0 "¡Aviones §Rno inventados§!!"
 PRODUCTION_SHIPS_BUTTON:0 "Construir barcos"
 PRODUCTION_SHIPS_BUTTON_DISABLED:0 "¡Barcos §Rno inventados§!!"
 PRODUCTION_CONSUMER_GOODS:0 "Bienes de consumo"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§HBienes de consumo§!"
 PRODUCTION_CONSUMER_GOODS_DESC:0 "Con nuestra política económica actual, la gente espera que un $PERCENTAGE|H0%$ del total de fábricas que tenemos produzcan bienes de consumo. Esta necesidad solo se satisface con fábricas civiles. Disponemos de $OPERATIONAL|H$ fábricas, de las que $TRADE_USABLE|H$ se podrán usar para el comercio."
 PRODUCTION_CIV_AND_MIL_FACTORIES:0 "Fábricas civiles y militares: $KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES:0 "Fábricas de bienes de consumo necesarias: $KEY|H$"
 PRODUCTION_MATERIAL_COST_DESC:0 "§TEsta cadena de producción emplea $AMOUNT|0H$ unidades de $MATERIAL|H$.§!"
 PRODUCTION_LINE_CANCEL:3 "§GHaz clic para §Hcancelar§! esta línea de producción§!\n§GMayús + clic para §Hcancelar§! todas las líneas de producción§!"
 PRODUCTION_CREATE_VARIANT:0 "§HCrear variante§!"
 PRODUCTION_CANCEL_CONSTRUCTION:0 "§TCancelar esta construcción.§!"
 CONFIRMCANCELPRODUCTIONLINE_TITLE:0 "Cancelar cadena de producción"
 CONFIRMCANCELPRODUCTIONLINE_DESC:0 "¿Seguro que quieres §Rcancelar§! esta cadena de producción?"
 CONFIRMCANCELCONSTRUCTION_TITLE:0 "Cancelar construcción"
 CONFIRMCANCELCONSTRUCTION_DESC:0 "¿Seguro que quieres §Rcancelar§! la construcción de $CONSTRUCTION|H$ en $REGION|H$?"
 CONFIRMCANCELCONSTRUCTIONS_TITLE:0 "Cancelar construcciones"
 CONFIRMCANCELCONSTRUCTIONS_DESC:0 "¿Seguro que quieres §Rcancelar§! todas las construcciones?"
 PRODUCTION_EQUIPMENT_NEED:0 "Necesita: $AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE:0 "Desplegar a puerto: $BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET:0 "Desplegar a flota: $FLEET|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE:0 "El objetivo de despliegue $FLEET|H$ no tiene base."
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET:0 "Desplegar flota objetivo $FLEET|H$ con base en $STATE|H$."
 PRODUCTION_NAVAL_DEPLOYMENT_BASE:0 "Base del objetivo de despliegue en $STATE|H$."
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE:0 "No se establecido un objetivo de despliegue."
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE:0 "No desplegable"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT:0 "Automático"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING:0 "Desechando"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC:0 "No hay una base válida para el despliegue. La unidad se desechará tras completarse."
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING:0 "Almacenando"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM:0 "§GClic derecho para ir a la provincia§!"
 WEEKLY_PRODUCTION:0 "Producción semanal"
 PRODUCTION_WORKING_FACTORIES:0 "Este es el número de fábricas que se ocupan de una de tus cadenas de producción en este momento."
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY:0 "En uso: $VALUE|R$"
 PRODUCTION_MAX_EFFICIENCY_BASE:0 "Límite base: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT:0 "£prod_eff_cap  Límite de eficacia de producción: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT:0 "£prod_eff_cap  El límite de eficacia de producción determina el valor máximo de tu £prod_eff  eficacia de producción. Puede aumentar con £tech_mod tecnologías."
 PRODUCTION_RESOURCES_PER_FACTORY:0 "§HRecursos por fábrica para producir:§!"
 PRODUCTION_MATERIAL_NO_WASTE:0 "La cadena no desperdicia nada de este recurso."
 PRODUCTION_MATERIAL_WASTE:0 "La cadena desperdicia $WASTE|R2$ de este recurso."
 PRODUCTION_SPEED:0 "Velocidad de producción: $SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS:0 "§YRendimiento de producción modificado en:§!"
 INDUSTRIAL_CAPACITY_FACTOR:0 "Rendimiento de fábrica: $VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS:0 "Rendimiento de fábrica modificado en:"
 INDUSTRIAL_PROGRESS:0 "$BUILDING|H$: $PROGRESS|0H$/$COST|0H$ ($VALUE|0%H$) completado."
 INDUSTRIAL_PROGRESS_REPAIR:0 "Progreso de reparación de $BUILDING|H$: $PROGRESS|%0H$"
 INDUSTRIAL_BASE_SPEED:0 "Rendimiento de $FACTORIES|0H$ fábricas: $VALUE|H$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED:0 "En propiedad: $VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_BORROWED:0 "De exportaciones: $VAL|H$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED:1 "$AMOUNT|0G$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE:1 "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION:0 "Con el balance diario actual, §Ysatisfaremos§! nuestras necesidades en $VALUE|0Y$ días."
 PRODUCTION_EQUIPMENT_FILLED:0 "Nuestras necesidades están §Gsatisfechas§! por ahora."
 PRODUCTION_EQUIPMENT_LOSSES:0 "Ayer perdimos $VALUE|R$ de equipo."
 PROD_LINE_PLANE_DEST_RESERVES:1 "Trasladándose a las §Yreservas§!"
 PROD_LINE_PLANE_DEST_UPGRADING:2 "Se necesita para §Ymejoras§!"
 PROD_LINE_PLANE_DEST_REINFORCEMENT:2 "Se necesita para §Yrefuerzos§!"
 PROD_LINE_LAND_DEST_RESERVES:1 "Se está §Yacumulando§!"
 PROD_LINE_LAND_DEST_UPGRADING:2 "Se necesita para §Ymejoras§!"
 PROD_LINE_LAND_DEST_REINFORCEMENT:2 "Se necesita para §Yrefuerzos§!"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE:0 "Desechar edificio"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC:0 "¿Seguro que quieres §Rdesechar§! este edificio?"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE:0 "Cancelar construcción"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC:0 "¿Seguro que quieres §Rcancelar§! esta construcción?"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE:0 "Cancelar conversión"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC:0 "¿Seguro que quieres §Rcancelar§! esta conversión?"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE:0 "Iniciar conversión"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC:0 "¿Seguro que quieres §Rconvertir§! este edificio?"
 PRODUCTION_EFFICIENCY_GAIN_BASE:0 "Ganancia base diaria: $VAL|%Y$"
 PRODUCTION_RESOURCE_FACTOR:0 "Escasez de recursos: $VAL|%+$"
 PRODUCTION_UNITS_PER_DAY:0 "$UNITS|Y$ unidades al día"
 PRODUCTION_UNITS_PER_WEEK:0 "$UNITS|Y$ unidades a la semana"
 PRODUCTION_UNITS_PER_MONTH:0 "$UNITS|Y$ unidades al mes"
 PRODUCTION_UNITS_PER_YEAR:0 "$UNITS|Y$ unidades al año"
 PRODUCTION_FACTORY_ASSIGN_DESC:1 "Haz clic para asignar £factory_item $FACTORIES|Y$ §Yfábricas militares§! a esta línea de producción. Esto ofrece un rendimiento base de producción de £production_cost $OUTPUT|Y$ al día.\nEl rendimiento total se ve afectado por los §Yrecursos§!, la §Yeficacia de producción§! y otros §Ymodificadores de producción§!."
 PRODUCTION_DOCKYARD_ASSIGN_DESC:1 "Haz clic para asignar £naval_factory_icon $FACTORIES|Y$ §Yastilleros navales§! a esta línea de producción. Esto ofrece un rendimiento base de producción de £navprod_cost $OUTPUT|Y$ al día.\nEl rendimiento total se ve afectado por los §Yrecursos§! y otros §Ymodificadores de producción§!."
 PRODUCTION_BASE_OUTPUT:0 "Rendimiento base: $VALUE|Y$ x $MUL|Y$"
 PRODUCTION_EFF_GAIN_HINT:0 "§YVelocidad de ganancia de eficacia modificada en:§!"
 CARRIER_AIR_WING_COMPOSITION_TITLE:0 "Ajustar composición predeterminada de alas para este portaaviones"
 CARRIER_AIR_WING_LIMIT_DESC:0 "Capacidad de aeroplanos/portaaviones"
 CARRIER_AIR_WING_LIMIT_DESC_UNDER:0 "§YLa capacidad de este portaaviones no se aprovechará al máximo§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER:0 "§RExcederás la capacidad de este portaaviones y las alas estacionadas en él sufrirán una penalización§!"
 CARRIER_AIR_WING_INCREASE:0 "Aumentar cantidad\n§GCtrl + clic para aumentar en§! §H5§!\n§GMayús + clic para aumentar en§! §H10§!"
 CARRIER_AIR_WING_DECREASE:0 "Reducir cantidad\n§GCtrl + clic para reducir en§! §H5§!\n§GMayús + clic para reducir en§! §H10§!"
 PRODUCTION_LINE_CHANGE:0 "§GHaz clic para §Hcambiar§! el equipo producido.\nSi cambias a una versión nueva del mismo equipo, mantendrás algo de eficacia.\n§!§RPerderás todos los progresos en esta cadena.§!"
 PRODUCTION_EQUIPMENT_FILTER:0 "Equipo de infantería y artillería"
 PRODUCTION_ARMOR_FILTER:0 "Vehículos blindados"
 PRODUCTION_AIR_FILTER:0 "Aviones"
 PRODUCTION_CAPITAL_SHIPS_FILTER:0 "Buques capitales"
 PRODUCTION_SCREEN_SHIPS_FILTER:0 "Barcos protectores"
 PRODUCTION_OTHER_SHIPS_FILTER:0 "Otros barcos"
 PRODUCTION_FILTER_ARMS_FACTORIES:0 "Fábricas militares usadas"
 PRODUCTION_FILTER_DOCKYARDS:0 "Astilleros navales usados"
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER:0 "Mano de obra insuficiente"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE:0 "Cancelar todas las cadenas"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC:0 "¿Seguro que quieres §Rcancelar§! todas las cadenas de producción?"
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME:0 "$STATE$ ($LVL|Y$)"
 PRODUCTION_ENTRY_NEW:0 "NUEVO"
 PRODUCTION_ENTRY_OUTDATED:0 "OBSOLETO"
 PRODICTION_MIC_TRANSFERED:0 "$OVERLORD|Y$ usa $AMOUNT|Y$ de nuestras fábricas."
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT:0 "$AMOUNT|Y$ de las fábricas militares proceden de nuestros súbditos."
 PRODICTION_MIC_SENT_TO_OVERLORD:0 "$AMOUNT|R$ de nuestras fábricas militares son para nuestro gobernante, por lo que solo nos queda(n) $LEFT|H$."
 PRODUCTION_CIVILIAN_FACTORIES_FROM_SUBJECTS:0 "De súbditos: +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_MASTER:0 "Para el gobernante: $VAL|R$"
 PRODUCTION_VEHICLES_BUTTON_NO_FACTORIES_DISABLED:0 "¡No tenemos §Rfábricas militares§!!"
 PRODUCTION_INFANTRY_BUTTON_NO_FACTORIES_DISABLED:0 "¡No tenemos §Rfábricas militares§!!"
 PRODUCTION_AIRCRAFT_BUTTON_NO_FACTORIES_DISABLED:0 "¡No tenemos §Rfábricas militares§!!"
 PRODUCTION_SHIPS_BUTTON_NO_DEPLOY_DISABLED:0 "¡No tenemos §Rpuertos§!!"
 PRODUCTION_SHIPS_BUTTON_NO_FACTORIES_DISABLED:0 "¡No tenemos §Rastilleros§!!"
 PRODUCTION_LINE_CHANGE_NAVAL:0 "§GHaz clic para §Hcambiar§! el equipo producido.\n§!§RPerderás todo el progreso de esta línea.§!"
 PRODUCTION_FILTER_SHIFTCLICK:1 "§GMayús + clic§! para §Rocultar§! todo lo demás."
 PRODUCTION_PRODUCING_NO_FACTORIES:0 "§RSin fábricas asignadas§!"
 PRODUCTION_LINE_CONVERT_NO_EQUIPMENT_IN_STOCK:0 "§REn este momento, no tenemos equipo en reserva que podamos convertir en: $VARIANT|H$§!"
 PRODUCTION_LINE_CONVERT_HEADER:0 "Convertir de las reservas"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION:0 "Orden de conversión:"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY:0 "\n  $NUM|Y2$ de $VARIANT|G$ ($TYPE$) con coste: "
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY:0 "\n  $NUM|Y2$ de $VARIANT|G$ ($TYPE$)"
 PRODUCTION_LINE_CONVERT_RESOURCE_COST_ENTRY:0 "$NUM$£resources_strip|$FRAME$ "
 PRODUCTION_LINE_CONVERT_DESC:1 "Convertir de las reservas utilizará el §Hequipo obsoleto§! o §Hcapturado§! que haya en estas para convertirlos en los vehículos modificados que necesita la cadena de producción actual, a coste reducido. Esto seguirá así hasta que se agoten las reservas."
 PRODUCTION_LINE_CONVERT_SPEED_TOTAL:1 "Velocidad de conversión: §G+§!$SPD|G%0$"
 PRODUCTION_LINE_CONVERT_SPEED_BASE:0 "Base: $VAL|Y0%$"
 PRODUCTION_LINE_CONVERT_RES_NEED:0 "Recursos necesarios para convertir a partir de $NAME|Y$:"
 PRODUCTION_LINE_CONVERT_RES_NEED_ENTRY:0 "\n   £resources_strip|$FRAME$: ($NEW|Y0$-$OLD|G0$)=$SUM|R0$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE:0 "§HLicencias de producción§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL:0 "§HRendimiento de fábrica de licencias de producción§!\nTotal: $VALUE|+%$\nAnálisis:"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION:1 "§YDiferencia de tecnología de licencias§!:\n Base: $BASE|+%$\n Modificación total: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER:1 "§YModificador de licencias§!:\n Base: $BASE|+%$\n Modificación total: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION:0 "§YNo forma facción con el licenciador§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE:0 "§YSin licencias activas§!: $VALUE|+%$"
 LICENSED_PURCHASE_CIC_COST:1 "§YEsta licencia cuesta§!: £civ_factory $AMOUNT|Y$"
 PRODUCTION_LACKING_RESOURCES_FILTER:0 "Recursos satisfechos"
 PRODUCTION_STOCKPILING_FILTER:0 "Almacenando"
 PRODUCTION_REINFORCING_FILTER:0 "Reforzando"
 PRODUCTION_UPGRADING_FILTER:0 "Mejorando"
 PRODUCTION_OUTDATED_FILTER:0 "Modelos actualizados"
 PRODUCTION_FILTER_CLICK_TO_HIDE:0 "§GHaz clic§! para §Rocultar§! toda la categoría."
 PRODUCTION_FILTER_CLICK_TO_SHOW:0 "§GHaz clic§! para §Gmostrar§! toda la categoría."
 PRODUCTION_FILTER_SHIFTCLICK_AGAIN:0 "\n§GMayúsculas + clic§! para volver a §Gmostrarlo§! todo."
 PRODUCTION_FILTER_RIGHTCLICK:0 "\n§GHaz clic derecho§! para plegar o desplegar toda la categoría."
 PRODUCTION_DRAG_N_DROP:0 "§GArrastra y suelta§! para cambiar la §Yprioridad§!."
 PRODUCTION_COLLAPSE:0 "§GHaz clic§! para §Yplegar§!."
 PRODUCTION_EXPAND:0 "§GHaz clic§! para §Yexpandir§!."
 PRODUCTION_FACTORY_SCALE_UP:0 "§GHaz clic§! ampliar la vista a §Y$SCALE$x§!."
 PRODUCTION_FACTORY_SCALE_DOWN:0 "§GHaz clic§! de nuevo para reducir la vista a §Y1x§!."
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OTHERS:0 "De otros países: +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_OTHERS:0 "Entregado a otros países: $VAL|R$"
 PRODUCTION_ADD_FACTORIES_CLICK:0 "§GHaz clic§! para añadir §Y+1§!\n§GCtrl + clic§! para añadir §Y+5§!\n§GMayúsculas + clic§! para añadir §Y+10§!"
 PRODUCTION_SUB_FACTORIES_CLICK:0 "§GHaz clic§! para sustraer §Y-1§!\n§GCtrl + clic§! para sustraer §Y-5§!\n§GMayúsculas + clic§! para sustraer §Y-10§!"
 PRODUCTION_CLICK_TO_APPEND_OR_INSERT:0 "§GHaz clic§! para añadir una nueva cadena de producción al final.\n§GMayúsculas + clic§! para poner primera una nueva cadena de producción."
 PRODUCTION_CIVILIAN_FACTORIES_DAMAGED:0 "Dañado: $VAL|R$"
