l_french:
 PRODUCTION_PRODUCTION_LABEL:0 "Production"
 PRODUCTION_EQUIPMENTPOOL_LABEL:0 "En stock"
 PRODUCTION_EFFICIENCY_LABEL:0 "§TEfficacité§!"
 PRODUCTION_EQUIPMENT_LABEL:0 "Matériel"
 PRODUCTION_ADJUSTERS_LABEL:0 "Ajusteurs"
 PRODUCTION_MATERIALS_LABEL:0 "Matériaux"
 PRODUCTION_FACTORIES_LABEL:0 "Usines"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL:0 "Usines militaires"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL:0 "Chantiers navals"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "Usines civiles"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL:0 "Usines militaires disponibles"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL:0 "Chantiers navals disponibles"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL:0 "Usines civiles disponibles"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL:0 "§TMatériel de l'armée de terre et de l'armée de l'air§!"
 PRODUCTION_NAVAL_LABEL:0 "§TMatériel de la marine§!"
 PRODUCTION_BUILDINGS_LABEL:0 "§TConstruction de bâtiments§!"
 PRODUCTION_PRODUCING_DAILY:0 "$AMOUNT$/jour"
 PRODUCTION_PRODUCING_WEEKLY:0 "$AMOUNT$/semaine"
 PRODUCTION_PRODUCING_MONTHLY:0 "$AMOUNT$/mois"
 PRODUCTION_PRODUCING_YEARLY:0 "$AMOUNT$/année"
 PRODUCTION_PRODUCING_ETA_DATE:0 "Prochaine réalisation : $DATE$"
 PRODUCTION_REPAIRING_ETA_DATE:0 "Fin des réparations : $DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS:0 "Dans $AMOUNT$ jours"
 PRODUCTION_PRODUCING_ETA_WEEKS:0 "Dans $AMOUNT$ semaines"
 PRODUCTION_PRODUCING_ETA_MONTHS:0 "Dans $AMOUNT$ mois"
 PRODUCTION_PRODUCING_ETA_YEARS:0 "Dans $AMOUNT$ ans"
 PRODUCTION_PRODUCING_NEVER:1 "§RJamais§!"
 PRODUCTION_PRODUCING_NO_FACTORIES:0 "§RAucune usine affectée§!"
 PRODUCTION_PRODUCING_NONE:0 "§RAucune§!"
 PRODUCTION_CAN_NOT_DEPLOY:0 "§RImpossible de se déployer§!"
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER:0 "Main-d'œuvre insuffisante"
 PRODUCTION_INCREASE_PRIORITY_LABEL:0 "§GCliquer pour §Haugmenter la priorité§!.\nShift + clic pour donner à cette production la §Hpriorité la plus élevée§!.§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL:0 "§GCliquer pour §Hdiminuer la priorité§!.\nShift + clic pour donner à cette production la §Hpriorité la plus basse§!.§!"
 PRODUCTION_PRIORITY_DELAYED:0 "Les lignes de production dotées d'une priorité plus élevée auront accès aux ressources avant celles dotées d'une priorité plus basse."
 PRODUCTION_EFFICIENCY:0 "£prod_eff §TProductivité : $AMOUNT|H2%$§!"
 PRODUCTION_EFFICIENCY_MOD:0 "£prod_eff §TProductivité : $AMOUNT|Y2%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN:2 "£prod_eff §TProductivité : $AMOUNT|H2%$§! ($GAIN|H3%$ par jour)"
 PRODUCTION_EFFICIENCY_DESC:0 "§TProductivité moyenne des usines.\nL'efficacité de production s'accroît de $VALUE|H=2$%/unité produite répartie équitablement entre les usines actives.§!"
 PRODUCTION_RESOURCE_PENALTY:0 "§TManque de ressources : $AMOUNT|R2%$§!"
 PRODUCTION_ASSIGN_EQUIPMENT:0 "§TAffectez du matériel pour lancer la production.§!"
 PRODUCTION_MATERIALS_OIL:0 "Pétrole"
 PRODUCTION_MATERIALS_ALUMINIUM:0 "Aluminium"
 PRODUCTION_MATERIALS_RUBBER:0 "Caoutchouc"
 PRODUCTION_MATERIALS_CHROMIUM:0 "Chrome"
 PRODUCTION_MATERIALS_STEEL:0 "Acier"
 PRODUCTION_MATERIALS_TUNGSTEN:0 "Tungstène"
 PRODUCTION_MATERIAL_VAL:0 "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON:0 "Construire des blindés"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "Les blindés n'ont §Rpas encore été inventés§!."
 PRODUCTION_VEHICLES_BUTTON_NO_FACTORIES_DISABLED:0 "Nous n'avons §Raucune usine militaire§! où construire des blindés."
 PRODUCTION_INFANTRY_BUTTON:0 "Construire du matériel d'infanterie ou de l'artillerie"
 PRODUCTION_INFANTRY_BUTTON_DISABLED:0 "Le matériel d'infanterie et l'artillerie n'ont §Rpas encore été inventés§!."
 PRODUCTION_INFANTRY_BUTTON_NO_FACTORIES_DISABLED:0 "Nous n'avons §Raucune usine militaire§! où construire du matériel d'infanterie ou de l'artillerie."
 PRODUCTION_AIRCRAFT_BUTTON:0 "Construire des avions"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED:0 "Les avions n'ont §Rpas encore été inventés§!."
 PRODUCTION_AIRCRAFT_BUTTON_NO_FACTORIES_DISABLED:0 "Nous n'avons §Raucune usine militaire§! où construire des avions."
 PRODUCTION_SHIPS_BUTTON:0 "Construire des navires"
 PRODUCTION_SHIPS_BUTTON_DISABLED:0 "Les navires n'ont §Rpas encore été inventés§!."
 PRODUCTION_SHIPS_BUTTON_NO_DEPLOY_DISABLED:0 "Nous n'avons §Raucun port§!."
 PRODUCTION_SHIPS_BUTTON_NO_FACTORIES_DISABLED:0 "Nous n'avons §Raucun chantier naval§! où construire des navires."
 PRODUCTION_CONSUMER_GOODS_VALUE:0 "$VALUE$"
 PRODUCTION_CONSUMER_GOODS:0 "Biens de consommation"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§HBiens de consommation§!"
 PRODUCTION_CONSUMER_GOODS_DESC:0 "Avec notre politique économique actuelle, la population s'attend à ce que $PERCENTAGE|H0%$ de l'ensemble de nos usines produisent des biens de consommation. Seules les usines civiles se chargent de satisfaire ce besoin, ce qui nous laisse $OPERATIONAL|H$ usines, dont $TRADE_USABLE|H$ peuvent être utilisées pour le commerce."
 PRODUCTION_CIV_AND_MIL_FACTORIES:0 "Usines civiles et militaires : $KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES:0 "Usines de biens de consommation requises : $KEY|H$"
 PRODUCTION_MATERIAL_COST_DESC:0 "§TCette ligne de production utilise $AMOUNT|0H$ unités de $MATERIAL|H$.§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC:2 "§TIl faudrait $AMOUNT|0H$ unités de plus pour une efficacité totale.§!\nLa production va continuer à §Rvitesse réduite§!."
 PRODUCTION_LINE_CANCEL:3 "§GCliquer§! pour §Hsupprimer§! cette ligne de production.\n§GShift + clic§! pour les §Hsupprimer§! toutes."
 PRODUCTION_CREATE_VARIANT:0 "§HCréer une variante§!"
 PRODUCTION_CANCEL_CONSTRUCTION:0 "§TAnnulez cette construction.§!"
 PRODUCTION_VARIANT_OBSOLETE_YES:1 "Remettre en service"
 PRODUCTION_VARIANT_OBSOLETE_NO:1 "Mettre hors service"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC:0 "§GCliquer§! pour remettre cette variante en service. Cela la marquera comme un matériel à jour."
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC:0 "§GCliquer§! pour mettre cette variante hors service. Cela la marquera comme un matériel obsolète."
 TRADE_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE:0 "Suppression d'une ligne de production"
 CONFIRMCANCELPRODUCTIONLINE_DESC:0 "\nVoulez-vous vraiment §Rsupprimer§! cette ligne de production ?"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE:0 "Suppress. de toutes les lignes de prod."
 CONFIRMCANCELALLPRODUCTIONLINE_DESC:0 "\nVoulez-vous vraiment §Rsupprimer§!\ntoutes les lignes de production ?"
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE:0 "Changer le matériel produit"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC:0 "Voulez-vous vraiment §Rchanger§! le matériel produit ? Cela va faire perdre $DAYS|R$ jours de production."
 CONFIRMCANCELCONSTRUCTION_TITLE:0 "Annulation de construction"
 CONFIRMCANCELCONSTRUCTION_DESC:0 "\nVoulez-vous vraiment §Rannuler§! la construction\nde $CONSTRUCTION|H$ en $REGION|H$ ?"
 CONFIRMCANCELCONSTRUCTIONS_TITLE:0 "Annulation des constructions"
 CONFIRMCANCELCONSTRUCTIONS_DESC:0 "\nVoulez-vous vraiment §Rannuler§! toutes les constructions ?"
 INFINITY:0 "£infinity_icon"
 PRODUCTION_EQUIPMENT_NEED:0 "Requis : $AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE:0 "Déployer vers le port de $BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET:0 "Déployer vers la flotte de $FLEET|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE:0 "La flotte de déploiement $FLEET|H$ n'a pas de base."
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET:0 "Déployer vers la flotte $FLEET|H$ basée dans l'État de $STATE|H$."
 PRODUCTION_NAVAL_DEPLOYMENT_BASE:0 "Déployer vers la base de l'État de $STATE|H$."
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE:0 "Aucune cible de déploiement n'a été définie."
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE:0 "Non déployable"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT:0 "Auto"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING:0 "Effacement"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC:0 "Aucune base dans laquelle être déployé. L'unité sera effacée une fois terminée."
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING:0 "Stockage"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM:0 "§GClic droit pour accéder à la province§!"
 WEEKLY_PRODUCTION:0 "Production hebdomadaire"
 PRODUCTION_WORKING_FACTORIES:0 "Nombre d'usines travaillant actuellement sur l'une de nos lignes de production."
 PRODICTION_MIC_TRANSFERED:0 "$AMOUNT|Y$ de nos usines sont utilisées par $OVERLORD|Y$."
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT:0 "$AMOUNT|Y$ de nos usines militaires proviennent de nos dépendances."
 PRODICTION_MIC_SENT_TO_OVERLORD:0 "$AMOUNT|R$ de nos usines militaires sont utilisées par notre pays maître, ce qui nous en laisse $LEFT|H$."
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE:0 "Disponible pour la construction : $VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY:0 "Utilisées : $VALUE|R$"
 PRODUCTION_MAX_EFFICIENCY_BASE:0 "Capacité de base : $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT:0 "£prod_eff_cap Limite de productivité : $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT:0 "La £prod_eff_cap limite de productivité détermine la £prod_eff productivité maximale. Elle peut être augmentée par les £tech_mod technologies."
 PRODUCTION_RESOURCES_PER_FACTORY:0 "§HRessources nécessaires à la production dans chaque usine :§!"
 PRODUCTION_MATERIAL_NO_WASTE:0 "La ligne ne gaspille pas cette ressource."
 PRODUCTION_MATERIAL_WASTE:0 "La ligne gaspille $WASTE|R2$ de cette ressource."
 PRODUCTION_SPEED:0 "Vitesse de production : $SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS:0 "§YProduction modifiée par :§!"
 INDUSTRIAL_CAPACITY_FACTOR:0 "Production des usines : $VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS:0 "Production des usines modifiée par :"
 INDUSTRIAL_PROGRESS:0 "$BUILDING|H$ : construction à $VALUE|0%H$ ($PROGRESS|0H$/$COST|0H$)."
 INDUSTRIAL_PROGRESS_REPAIR:0 "Réparations de $BUILDING|H$ effectuées à $PROGRESS|%0H$"
 INDUSTRIAL_BASE_FACTORY_OUTPUT:0 "Production de base des usines : $VALUE|H$"
 INDUSTRIAL_BASE_SPEED:0 "Production de $FACTORIES|0H$ usines : $VALUE|H$"
 PROD_COST_VALUE:0 "$VALUE$£production_cost "
 NAVPROD_COST_VALUE:0 "$VALUE$£navprod_cost "
 PRODUCTION_CIVILIAN_FACTORIES_OWNED:0 "Possédées : $VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_BORROWED:0 "Grâce aux exportations : +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_SUBJECTS:0 "Des dépendances : +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_MASTER:0 "Données au pays maître : $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OTHERS:0 "Reçues d'autres pays : +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_OTHERS:0 "Données à d'autres pays : $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_DAMAGED:0 "Endommagées : $VAL|R$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED:2 "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED:1 "$AMOUNT|0G$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE:1 "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE:0 "Solde journalier : $VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION:0 "Avec le solde quotidien actuel, nos besoins seront §Ysatisfaits§! dans $VALUE|0Y$ jours."
 PRODUCTION_EQUIPMENT_FILLED:0 "Nos besoins sont §Gsatisfaits§! pour le moment."
 PRODUCTION_EQUIPMENT_LOSSES:0 "Nous avons perdu $VALUE|R$ équipements hier."
 PROD_LINE_PLANE_DEST_RESERVES:1 "Mis en §Yréserve§!."
 PROD_LINE_PLANE_DEST_UPGRADING:2 "Nécessaire pour les §Yaméliorations§!."
 PROD_LINE_PLANE_DEST_REINFORCEMENT:2 "Nécessaire pour les §Yrenforts§!."
 PROD_LINE_LAND_DEST_RESERVES:1 "Mis en §Yréserve§!."
 PROD_LINE_LAND_DEST_UPGRADING:2 "Nécessaire pour les §Yaméliorations§!."
 PROD_LINE_LAND_DEST_REINFORCEMENT:2 "Nécessaire pour les §Yrenforts§!."
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE:0 "Supprimer un niveau du bâtiment"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC:0 "Voulez-vous vraiment §Rsupprimer§! ce bâtiment ?"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE:0 "Annuler une construction"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC:0 "Voulez-vous vraiment §Rannuler§! cette construction ?"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE:0 "Annuler une conversion"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC:0 "Voulez-vous vraiment §Rannuler§! cette conversion ?"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE:0 "Lancer une conversion"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC:0 "Voulez-vous vraiment §Rconvertir§! ce bâtiment ?"
 PRODUCTION_EFFICIENCY_GAIN_BASE:0 "Gain de base quotidien : $VAL|%Y$"
 PRODUCTION_RESOURCE_FACTOR:0 "Manque de ressources : $VAL|%+$"
 PRODUCTION_OUTPUT_EXPLAIN:0 "Nos $FACTORIES|Y$ £factory_item usines militaires produisent $OUTPUT|Y$£production_cost .\n$ITEM|Y$ ayant un coût de production de $ITEM_COST|2Y$ £production_cost , nous pouvons en produire $PERTIMEPERIOD$.\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL:0 "Nos $FACTORIES|Y$ chantiers £naval_factory_icon produisent $OUTPUT|Y$£navprod_cost .\n$ITEM|Y$ ayant un coût de production de $ITEM_COST|2Y$ £navprod_cost , nous pouvons en produire $PERTIMEPERIOD$.\n"
 PRODUCTION_UNITS_PER_DAY:0 "$UNITS|Y$ unités par jour"
 PRODUCTION_UNITS_PER_WEEK:0 "$UNITS|Y$ unités par semaine"
 PRODUCTION_UNITS_PER_MONTH:0 "$UNITS|Y$ unités par mois"
 PRODUCTION_UNITS_PER_YEAR:0 "$UNITS|Y$ unités par an"
 PRODUCTION_FACTORY_ASSIGN_DESC:1 "Cliquer pour affecter $FACTORIES|Y$ £factory_item §Yusines militaires§! à cette ligne de production. Cela va permettre une production de base de $OUTPUT|Y$£production_cost  par jour.\nLa production totale dépendra des §Yressources§!, de la §Yproductivité§! et des autres §Ymodificateurs de production§!."
 PRODUCTION_DOCKYARD_ASSIGN_DESC:1 "Cliquer pour affecter $FACTORIES|Y$ £naval_factory_icon §Ychantiers navals§! à cette ligne de production. Cela va permettre une production de base de $OUTPUT|Y$£navprod_cost  par jour.\nLa production totale dépendra des §Yressources§!, de la §Yproductivité§! et des autres §Ymodificateurs de production§!."
 PRODUCTION_BASE_OUTPUT:0 "Production de base : $VALUE|Y$ x $MUL|Y$"
 PRODUCTION_EFF_GAIN_HINT:0 "§YVitesse du gain d'efficacité modifiée par :§!"
 CARRIER_AIR_WING_COMPOSITION_TITLE:0 "Composition par défaut des escadrilles de ce type de porte-avions."
 CARRIER_AIR_WING_LIMIT_UNDER:0 "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH:0 "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER:0 "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC:0 "Nombre d'appareils embarqués sur ce type de porte-avions."
 CARRIER_AIR_WING_LIMIT_DESC_UNDER:0 "§YCe type de porte-avions ne sera pas employé à la hauteur de ses capacités.§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER:0 "§RLa capacité de ce type de porte-avions sera dépassée. Ses escadrilles subiront donc une pénalité.§!"
 CARRIER_AIR_WING_INCREASE:0 "Augmenter le nombre d'appareils\n§GCtrl+clic§! pour augmenter de §H5§!.\n§GShift+clic§! pour augmenter de §H10§!."
 CARRIER_AIR_WING_DECREASE:0 "Réduire le nombre d'appareils\n§GCtrl+clic§! pour réduire de §H5§!.\n§GShift+clic§! pour réduire de §H10§!."
 PRODUCTION_ENTRY_NEW:0 "§GNOUVEAU§!"
 PRODUCTION_ENTRY_OUTDATED:0 "§HOBSOLÈTE§!"
 PRODUCTION_LINE_CHANGE:0 "§GCliquer pour §Hchanger§! de production.\nUne partie de l'efficacité de la ligne de production sera conservée si vous passez à une version plus récente du même matériel.\n§!§RTous les progrès de cette ligne seront perdus.§!"
 PRODUCTION_LINE_CHANGE_NAVAL:0 "§GCliquer pour §Hchanger§! de production.\n§!§RTous les progrès de cette ligne de production seront perdus.§!"
 PRODUCTION_EQUIPMENT_FILTER:0 "Matériel d'infanterie et d'artillerie"
 PRODUCTION_ARMOR_FILTER:0 "Blindés"
 PRODUCTION_AIR_FILTER:0 "Avions"
 PRODUCTION_CAPITAL_SHIPS_FILTER:0 "Navires capitaux"
 PRODUCTION_SCREEN_SHIPS_FILTER:0 "Navires d'escorte"
 PRODUCTION_OTHER_SHIPS_FILTER:0 "Autres navires"
 PRODUCTION_LACKING_RESOURCES_FILTER:0 "Réserves pleines"
 PRODUCTION_STOCKPILING_FILTER:0 "Réserves"
 PRODUCTION_REINFORCING_FILTER:0 "Renforts"
 PRODUCTION_UPGRADING_FILTER:0 "Améliorations"
 PRODUCTION_OUTDATED_FILTER:0 "Modèles à jour"
 PRODUCTION_FILTER_CLICK_TO_HIDE:0 "§GCliquer§! pour §Rmasquer§! tout ce qui relève de cette catégorie."
 PRODUCTION_FILTER_CLICK_TO_SHOW:0 "§GCliquer§! pour §Gafficher§! tout ce qui relève de cette catégorie."
 PRODUCTION_FILTER_SHIFTCLICK:1 "\n§GShift+clic§! pour §Rmasquer§! tout ce qui ne relève pas de cette catégorie."
 PRODUCTION_FILTER_SHIFTCLICK_AGAIN:0 "\n§GShift+clic§! pour §Gafficher§! tout à nouveau."
 PRODUCTION_FILTER_RIGHTCLICK:0 "\n§GClic droit§! pour masquer ou afficher tout ce qui relève de cette catégorie."
 PRODUCTION_FILTER_ARMS_FACTORIES:0 "Usines militaires utilisées"
 PRODUCTION_FILTER_DOCKYARDS:0 "Chantiers navals utilisés"
 PRODUCTION_DRAG_N_DROP:0 "§GCliquer et faire glisser§! pour modifier la §Ypriorité§!."
 PRODUCTION_COLLAPSE:0 "§GCliquer§! pour §Ymasquer§!."
 PRODUCTION_EXPAND:0 "§GCliquer§! pour §Yafficher§!."
 PRODUCTION_FACTORY_SCALE_UP:0 "§GCliquer§! pour afficher par groupes de §Y$SCALE$§!."
 PRODUCTION_FACTORY_SCALE_DOWN:0 "§GCliquer§! pour afficher §Yindividuellement§!."
 PRODUCTION_ADD_FACTORIES_CLICK:0 "§GCliquer§! pour en ajouter §Y1§!.\n§GCtrl + clic§! pour en ajouter §Y5§!.\n§GShift + clic§! pour en ajouter §Y10§!."
 PRODUCTION_SUB_FACTORIES_CLICK:0 "§GCliquer§! pour en retirer §Y1§!.\n§GCtrl + clic§! pour en retirer §Y5§!.\n§GShift + clic§! pour en retirer §Y10§!."
 PRODUCTION_CLICK_TO_APPEND_OR_INSERT:0 "§GCliquer§! pour ajouter une nouvelle ligne de production en bas de liste.\n§GShift + clic§! pour en ajouter une nouvelle en haut de liste."
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME:0 "$STATE$ ($LVL|Y$)"
 PRODUCTION_LINE_CONVERT_NO_EQUIPMENT_IN_STOCK:0 "§RIl n'y a actuellement aucun matériel en réserve qui pourrait être converti en $VARIANT|H$§!."
 PRODUCTION_LINE_CONVERT_HEADER:0 "Convertir les réserves"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION:0 "Ordre de conversion :"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY:0 "\n  $NUM|Y2$ unités de $VARIANT|G$ (§H$TYPE$§!) pour un coût de : "
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY:0 "\n  $NUM|Y2$ unités de $VARIANT|G$ (§H$TYPE$§!)"
 PRODUCTION_LINE_CONVERT_RESOURCE_COST_ENTRY:0 "§H$NUM$§!£resources_strip|$FRAME$ "
 PRODUCTION_LINE_CONVERT_DESC:1 "Convertir les réserves va modifier le §Hmatériel dépassé§! ou §Hcapturé§! pour l'adopter à la demande des lignes de production pour un coût réduit. Cela sera fait jusqu'à épuisement du matériel en réserve."
 PRODUCTION_LINE_CONVERT_SPEED_TOTAL:1 "Vitesse de conversion : §G+§!$SPD|G%0$"
 PRODUCTION_LINE_CONVERT_SPEED_BASE:0 "Base : $VAL|Y0%$"
 PRODUCTION_LINE_CONVERT_RES_NEED:0 "Ressources nécessaires pour la conversion des $NAME|Y$ :"
 PRODUCTION_LINE_CONVERT_RES_NEED_ENTRY:0 "\n   £resources_strip|$FRAME$ : ($NEW|Y0$ - $OLD|G0$) = $SUM|R0$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE:0 "§HProduction sous licence§! : $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL:0 "§HProduction des usines sous licence§!\nTotal : $VALUE|+%$\nDégradation :"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION:1 "§YDifférence technologique de la licence§! :\n Base : $BASE|+%$\n Total modifié : $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER:1 "§YModificateur de licence§!:\n Base : $BASE|+%$\n Total modifié : $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION:0 "§YPas dans la même faction que le concédeur de licence§! : $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE:0 "§YActuellement aucune licence§! : $VALUE|+%$"
 LICENSED_PURCHASE_CIC_COST:1 "§YCoût de la licence§! : $AMOUNT|Y$£civ_factory£"


######################
###  TO BE ERASED  ###
######################
# PRODUCTION_CIVILIAN_FACTORIES_TOTAL:0 "Total des usines civiles : $VALUE|Y$"
# PRODUCTION_VARIANT_OBSOLETE_DESC:0 "§GCliquez pour basculer.§!"
# PROD_LINE_PLANE_DEST:0 " §Y(en réserve)§!"
